#define SEMICOLON                       1
#define COMMA                           2
#define COLON                           3
#define PERIOD                          4
#define LPAREN                          5
#define RPAREN                          6
#define LBRACE                          7
#define RBRACE                          8
#define LBRACKET                        9
#define RBRACKET                       10
#define AND                            11
#define OR                             12
#define XOR                            13
#define COMPLEMENT                     14
#define NOT                            15
#define QUESTION                       16
#define PLUS                           17
#define MINUS                          18
#define TIMES                          19
#define DIVIDE                         20
#define PERCENT                        21
#define LSHIFT                         22
#define RSHIFT                         23
#define ANDAND                         24
#define OROR                           25
#define GT                             26
#define LT                             27
#define LEQ                            28
#define GEQ                            29
#define EQL                            30
#define NEQ                            31
#define EOL                            32
#define EOI                            33
#define Q3MAP_SUN                      34
#define Q3MAP_FANCYWATER               35
#define Q3MAP_CHEAPWATER               36
#define Q3MAP_NOFANCYWATER             37
#define DEFORM                         38
#define NORMAL                         39
#define MOVE                           40
#define BULGE                          41
#define PROJSHADOW                     42
#define AUTOSPRITE                     43
#define AUTOSPRITE2                    44
#define TEXT                           45
#define TESSSIZE                       46
#define CLAMPTIME                      47
#define SURFACEPARM                    48
#define NOMIPMAPS                      49
#define NOPICMIP                       50
#define POLYGONOFFSET                  51
#define ENTITYMERGABLE                 52
#define FOGPARMS                       53
#define SKYPARMS                       54
#define LIGHT                          55
#define WAVE                           56
#define PORTAL                         57
#define CULL                           58
#define CULLTYPE                       59
#define SORT                           60
#define SORTTYPE                       61
#define MAP                            62
#define CLAMPMAP                       63
#define ANIMMAP                        64
#define VIDEOMAP                       65
#define WHITEIMAGE                     66
#define LIGHTMAP                       67
#define ALPHAFUNC                      68
#define ALPHAMODE                      69
#define BLENDFUNC                      70
#define BLENDMODE                      71
#define DEPTHFUNC                      72
#define DEPTHMODE                      73
#define CGEN                           74
#define CGENTYPE                       75
#define AGEN                           76
#define AGENTYPE                       77
#define TCGEN                          78
#define TCGENTYPE                      79
#define TCMOD                          80
#define TURB                           81
#define SCALE                          82
#define SCROLL                         83
#define STRETCH                        84
#define TRANSFORM                      85
#define ROTATE                         86
#define ENTITYTRANSLATE                87
#define CONST                          88
#define VECTOR                         89
#define GENFUNC                        90
#define DETAIL                         91
#define DEPTHWRITE                     92
#define INTEGER                        93
#define FLOAT                          94
#define STRING                         95
#define PATH                           96
#define ERROR                          97
#define IDENTIFIER                     98
#define NOPICMIPS                      99
#define DBLENDMODE                     100
#define SBLENDMODE                     101
#define STETCH                         102
